/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
                        "surface-variant": "#e2e1ed",
                        "tertiary-fixed-dim": "#ffb59d",
                        "error": "#ba1a1a",
                        "secondary-fixed-dim": "#88d982",
                        "on-surface-variant": "#454652",
                        "inverse-on-surface": "#f1f0fb",
                        "on-secondary-fixed": "#002204",
                        "on-background": "#1a1b23",
                        "tertiary": "#380b00",
                        "on-primary-fixed": "#000767",
                        "primary": "#000666",
                        "secondary-fixed": "#a3f69c",
                        "primary-container": "#1a237e",
                        "surface-bright": "#fbf8ff",
                        "inverse-primary": "#bdc2ff",
                        "outline": "#767683",
                        "error-container": "#ffdad6",
                        "on-primary": "#ffffff",
                        "on-error-container": "#93000a",
                        "on-secondary": "#ffffff",
                        "surface-container-lowest": "#ffffff",
                        "surface-dim": "#dad9e4",
                        "tertiary-container": "#5c1800",
                        "on-secondary-container": "#217128",
                        "background": "#fbf8ff",
                        "surface-container-highest": "#e2e1ed",
                        "on-error": "#ffffff",
                        "on-secondary-fixed-variant": "#005312",
                        "outline-variant": "#c6c5d4",
                        "secondary-container": "#a0f399",
                        "surface-container-low": "#f3f2fe",
                        "on-surface": "#1a1b23",
                        "on-primary-fixed-variant": "#343d96",
                        "surface-container": "#eeedf8",
                        "primary-fixed": "#e0e0ff",
                        "inverse-surface": "#2f3038",
                        "on-tertiary-container": "#e17c5a",
                        "tertiary-fixed": "#ffdbd0",
                        "on-tertiary-fixed": "#390c00",
                        "surface": "#fbf8ff",
                        "on-tertiary": "#ffffff",
                        "primary-fixed-dim": "#bdc2ff",
                        "on-tertiary-fixed-variant": "#7b2e12",
                        "surface-container-high": "#e8e7f2",
                        "secondary": "#1b6d24",
                        "on-primary-container": "#8690ee",
                        "surface-tint": "#4c56af"
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
